import { Component } from '@angular/core';

@Component({
  selector: 'app-badajoz',
  imports: [],
  templateUrl: './badajoz.component.html',
  styleUrl: './badajoz.component.css',
})
export class BadajozComponent {
  rutas = [
    {
      nombre: 'Ruta del Río Guadiana',
      salida: 'Badajoz',
      llegada: 'Riberas del Guadiana',
      km: 6,
      dificultad: 'Fácil',
      duracion: '2 h',
      tipo: 'Circular',
      imagen: 'images/badajoz/rio-guadiana-ruta.jpg',
      maps: 'https://www.google.com/maps/search/Rio+Guadiana+Badajoz',
      wikiloc:
        'https://www.wikiloc.com/wikiloc/map.do?query=Ruta+del+Rio+Guadiana+Badajoz',
    },
    {
      nombre: 'Sendero del Fuerte de San Cristóbal',
      salida: 'Badajoz',
      llegada: 'Fuerte de San Cristóbal',
      km: 4,
      dificultad: 'Fácil',
      duracion: '1,5 h',
      tipo: 'Circular',
      imagen: 'images/badajoz/fuerte-san-cristobal-badajoz.jpg',
      maps: 'https://www.google.com/maps/search/Fuerte+de+San+Cristobal+Badajoz',
      wikiloc:
        'https://www.wikiloc.com/trails/hiking/fuerte-de-san-cristobal-badajoz',
    },
    {
      nombre: 'Ruta de la Alcazaba y Murallas',
      salida: 'Casco antiguo',
      llegada: 'Alcazaba de Badajoz',
      km: 3,
      dificultad: 'Fácil',
      duracion: '1,5 h',
      tipo: 'Circular',
      imagen: 'images/badajoz/alcazaba-muralla.png',
      maps: 'https://www.google.com/maps/search/Alcazaba+de+Badajoz',
      wikiloc: 'https://www.wikiloc.com/trails/hiking/alcazaba-de-badajoz',
    },
    {
      nombre: 'Sendero del Parque del Guadiana',
      salida: 'Puente de Palmas',
      llegada: 'Parque fluvial',
      km: 7,
      dificultad: 'Fácil',
      duracion: '2,5 h',
      tipo: 'Lineal',
      imagen: 'images/badajoz/rio-guadiana.jpg',
      maps: 'https://www.google.com/maps/search/Parque+del+Guadiana+Badajoz',
      wikiloc:
        'https://www.wikiloc.com/trails/hiking/parque-del-guadiana-badajoz',
    },
    {
      nombre: 'Ruta de las Dehesas Extremeñas',
      salida: 'Valverde de Leganés',
      llegada: 'Dehesas ganaderas',
      km: 8,
      dificultad: 'Media',
      duracion: '3 h',
      tipo: 'Circular',
      imagen: 'images/badajoz/dehesa-extremeña.jpg',
      maps: 'https://www.google.com/maps/search/Valverde+de+Leganes',
      wikiloc:
        'https://www.wikiloc.com/trails/hiking/dehesas-de-valverde-de-leganes',
    },
    {
      nombre: 'Sendero del Embalse de Alqueva',
      salida: 'Cheles',
      llegada: 'Embalse de Alqueva',
      km: 6,
      dificultad: 'Fácil',
      duracion: '2,5 h',
      tipo: 'Circular',
      imagen: 'images/badajoz/alqueva.jpg',
      maps: 'https://www.google.com/maps/search/Embalse+de+Alqueva+Cheles',
      wikiloc:
        'https://www.wikiloc.com/trails/hiking/embalse-de-alqueva-cheles',
    },
    {
      nombre: 'Ruta del Camino Natural del Guadiana',
      salida: 'Badajoz',
      llegada: 'Talavera la Real',
      km: 10,
      dificultad: 'Media',
      duracion: '3,5 h',
      tipo: 'Lineal',
      imagen: 'images/badajoz/camino-natural-guadiana.jpg',
      maps: 'https://www.google.com/maps/search/Camino+Natural+del+Guadiana',
      wikiloc:
        'https://www.wikiloc.com/trails/hiking/camino-natural-del-guadiana',
    },
    {
      nombre: 'Ruta de los Miradores del Guadiana',
      salida: 'Cerro Gordo',
      llegada: 'Miradores naturales',
      km: 5,
      dificultad: 'Fácil',
      duracion: '1,5 h',
      tipo: 'Circular',
      imagen: 'images/badajoz/ruta-miradores.jpg',
      maps: 'https://www.google.com/maps/search/Miradores+Guadiana+Badajoz',
      wikiloc:
        'https://www.wikiloc.com/trails/hiking/miradores-del-guadiana-badajoz',
    },
    {
      nombre: 'Sendero de la Dehesa de San Pedro',
      salida: 'Alburquerque',
      llegada: 'Dehesa de encinas',
      km: 7,
      dificultad: 'Fácil',
      duracion: '2 h',
      tipo: 'Circular',
      imagen: 'images/badajoz/miradores-del-guadiana.png',
      maps: 'https://www.google.com/maps/search/Dehesa+San+Pedro+Badajoz',
      wikiloc:
        'https://www.wikiloc.com/trails/hiking/dehesa-de-san-pedro-alburquerque',
    },
    {
      nombre: 'Ruta Nocturna del Casco Histórico',
      salida: 'Plaza Alta',
      llegada: 'Murallas iluminadas',
      km: 3,
      dificultad: 'Fácil',
      duracion: '1 h',
      tipo: 'Circular',
      imagen: 'images/badajoz/ruta-nocturena-badajoz.jpg',
      maps: 'https://www.google.com/maps/search/Plaza+Alta+Badajoz',
      wikiloc: 'https://www.wikiloc.com/trails/hiking/ruta-nocturna-badajoz',
    },
  ];
}
